### ISSUE TITLE
Create Release

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.BuildingBlockTemplates#9]
@Yuri05 I am not sure how we should version this. We need to create a release however

**Comment by Yuri05** [comment]
My first thought was: set the major release version = major version of the ospsuite (so 11.0 for now) etc. - but as we will not  nesessarily update it with every OSP release - it might diverge in the future.

So let's keep it simple: 1.0 :)

**Comment by msevestre** [comment]
Agreed

**Comment by Yuri05** [comment]
Release 1.0 created
